name: Build & Test
on:
  push:
    branches:
    - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - run: yarn install --frozen-lockfile
    - run: yarn build
    - run: yarn test
    - run: mkdir -p reports
    - run: yarn verify
    - name: Archive build reports
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: reports
    - name: define SONAR_VERSION env variable
      run: |
        echo "SONAR_VERSION=$(npx project-version)" >> $GITHUB_ENV
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectVersion=${{ env.SONAR_VERSION }}
